"""Add models

Revision ID: e280971166ca
Revises: b3f676ce595c
Create Date: 2023-03-26 15:51:56.747683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e280971166ca'
down_revision = 'b3f676ce595c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)
    op.create_index(op.f('ix_attributes_name'), 'attributes', ['name'], unique=False)
    op.create_index(op.f('ix_attributes_value'), 'attributes', ['value'], unique=False)
    op.create_table('houses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_last_version', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('predicted_price', sa.Integer(), nullable=True),
    sa.Column('predicted_rental_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('inserted_at', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_created_at'), 'houses', ['created_at'], unique=False)
    op.create_index(op.f('ix_houses_currency'), 'houses', ['currency'], unique=False)
    op.create_index(op.f('ix_houses_data_source'), 'houses', ['data_source'], unique=False)
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.create_index(op.f('ix_houses_inserted_at'), 'houses', ['inserted_at'], unique=False)
    op.create_index(op.f('ix_houses_internal_id'), 'houses', ['internal_id'], unique=False)
    op.create_index(op.f('ix_houses_predicted_price'), 'houses', ['predicted_price'], unique=False)
    op.create_index(op.f('ix_houses_predicted_rental_price'), 'houses', ['predicted_rental_price'], unique=False)
    op.create_index(op.f('ix_houses_price'), 'houses', ['price'], unique=False)
    op.create_index(op.f('ix_houses_updated_at'), 'houses', ['updated_at'], unique=False)
    op.create_index(op.f('ix_houses_url'), 'houses', ['url'], unique=True)
    op.create_table('house_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_attributes_id'), 'house_attributes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_house_attributes_id'), table_name='house_attributes')
    op.drop_table('house_attributes')
    op.drop_index(op.f('ix_houses_url'), table_name='houses')
    op.drop_index(op.f('ix_houses_updated_at'), table_name='houses')
    op.drop_index(op.f('ix_houses_price'), table_name='houses')
    op.drop_index(op.f('ix_houses_predicted_rental_price'), table_name='houses')
    op.drop_index(op.f('ix_houses_predicted_price'), table_name='houses')
    op.drop_index(op.f('ix_houses_internal_id'), table_name='houses')
    op.drop_index(op.f('ix_houses_inserted_at'), table_name='houses')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_index(op.f('ix_houses_data_source'), table_name='houses')
    op.drop_index(op.f('ix_houses_currency'), table_name='houses')
    op.drop_index(op.f('ix_houses_created_at'), table_name='houses')
    op.drop_table('houses')
    op.drop_index(op.f('ix_attributes_value'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_name'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
